map_type: costmap

obstacle_range: 2.5
raytrace_range: 3.5
footprint: [[-0.1, 0.2], [0.1, 0.2], [0.1, -0.2], [-0.1, -0.2]]
transform_tolerance: 0.3

inflation_radius: 1.75

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /udacity_bot/laser/scan, marking: true, clearing: true}