map_type: costmap

obstacle_range: 2.5
raytrace_range: 3.5
transform_tolerance: 0.3

robot_radius: 0.2
inflation_radius: 1.75

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /custom_bot/laser/scan, marking: true, clearing: true}